repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.2.0"
    hooks:
      - id: ruff
        # Autofix, and respect `exclude` and `extend-exclude` settings.
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
